<?php
require_once __DIR__ . '/../config.php';
requireAuth();
$pageTitle = 'Gold Give Details';
$id = (int) query('id', 0); $db = getDB();
$stmt = $db->prepare("SELECT g.*, c.name as customer_name, c.phone as customer_phone FROM gold_gives g LEFT JOIN customers c ON c.id=g.customer_id WHERE g.id=? AND g.deleted_at IS NULL"); $stmt->execute([$id]); $give=$stmt->fetch();
if(!$give){ setFlash('error','Gold give not found.'); redirect('gold-gives/index.php'); }
$stmt=$db->prepare("SELECT * FROM gold_give_items WHERE give_id=?"); $stmt->execute([$id]); $items=$stmt->fetchAll();
require_once __DIR__ . '/../includes/header.php';
?>
<div class="page-header"><div class="page-title-group"><h1><?= htmlspecialchars($give['give_no']) ?></h1><p class="font-urdu" style="margin-top:4px;">سونا دیا تفصیلات</p></div><div class="page-actions"><a href="<?= url('gold-gives/edit.php?id='.$id) ?>" class="btn btn-primary"><i class="bi bi-pencil"></i> Edit</a><a href="<?= url('gold-gives/print.php?id='.$id) ?>" class="btn btn-success"><i class="bi bi-printer"></i> Print</a><a href="<?= url('gold-gives/delete.php?id='.$id) ?>" class="btn btn-danger" onclick="return confirm('Delete this gold give?')"><i class="bi bi-trash"></i> Delete</a><a href="<?= url('gold-gives/index.php') ?>" class="btn btn-outline"><i class="bi bi-arrow-left"></i> Back</a></div></div>
<div class="invoice-detail-grid"><div class="detail-card"><h3>Give Information</h3><div class="detail-row"><span class="detail-label">Give No</span><span class="detail-value"><?= htmlspecialchars($give['give_no']) ?></span></div><div class="detail-row"><span class="detail-label">Date</span><span class="detail-value"><?= formatDate($give['give_date']) ?></span></div><div class="detail-row"><span class="detail-label">Type</span><span class="detail-value"><span class="badge bg-info"><?= ucfirst($give['give_type']) ?></span></span></div><?php if($give['remarks']): ?><div class="detail-row"><span class="detail-label">Remarks</span><span class="detail-value"><?= htmlspecialchars($give['remarks']) ?></span></div><?php endif; ?></div><div class="detail-card"><h3>Party</h3><div class="detail-row"><span class="detail-label">Name</span><span class="detail-value"><a href="<?= url('customers/show.php?id='.$give['customer_id']) ?>" style="color:var(--gold-primary);"><?= htmlspecialchars($give['customer_name'] ?? 'N/A') ?></a></span></div><div class="detail-row"><span class="detail-label">Phone</span><span class="detail-value"><?= htmlspecialchars($give['customer_phone'] ?? '-') ?></span></div></div></div>
<div class="card" style="padding:24px;margin-top:24px;"><h3 style="font-family:'Playfair Display',serif;margin-bottom:16px;color:var(--gold-primary);">Items Given</h3><div class="table-container"><table><thead><tr><th>Description</th><th class="text-right">Gross Weight (g)</th><th class="text-right">Ratti Impurity</th><th class="text-right">Khalis Given (g)</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?= htmlspecialchars($item['description'] ?: '-') ?></td><td class="text-right mono"><?= number_format($item['gross_weight'],3) ?></td><td class="text-right mono"><?= number_format($item['ratti_impurity'],3) ?></td><td class="text-right mono text-danger" style="font-weight:600;"><?= number_format($item['khalis_weight'],3) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr style="font-weight:700;background:var(--bg-surface);"><td>Total</td><td class="text-right mono"><?= number_format($give['total_gross_weight'],3) ?></td><td></td><td class="text-right mono text-danger"><?= number_format($give['total_khalis_weight'],3) ?></td></tr></tfoot></table></div></div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
