<?php
require_once __DIR__ . '/../config.php';
requireAuth();

$id = (int) query('id', 0);
$db = getDB();

$stmt = $db->prepare("SELECT r.*, c.name as customer_name, c.phone as customer_phone, c.address as customer_address FROM gold_receipts r LEFT JOIN customers c ON c.id = r.customer_id WHERE r.id = ?");
$stmt->execute([$id]);
$receipt = $stmt->fetch();
if (!$receipt) { redirect('gold-receipts/index.php'); }

$stmt = $db->prepare("SELECT * FROM gold_receipt_items WHERE receipt_id = ?");
$stmt->execute([$id]);
$items = $stmt->fetchAll();

$wsName = getSetting('workshop_name', 'M.J Casting');
$wsNameUrdu = getSetting('workshop_name_urdu', 'ایم جے کاسٹنگ');
$wsAddress = getSetting('address', '');
$wsPhone = getSetting('phone', '');
$wsCity = getSetting('city', '');
$format = query('format', 'slip');
$hideSidebar = true;
$pageTitle = 'Print Receipt';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Print - <?= htmlspecialchars($receipt['receipt_no']) ?></title>
    <style>
        body { margin:0; padding:0; background:#fff; color:#000; font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif; -webkit-print-color-adjust:exact; }
        .print-container { margin:0 auto; }
        .format-slip { width:80mm; padding:3mm; }
        .format-a5 { width:148mm; padding:8mm; }
        .print-header { text-align:center; border-bottom:2px double #000; padding-bottom:12px; margin-bottom:12px; }
        .print-header h2 { margin:0; font-size:18px; }
        .print-header h3 { margin:4px 0; font-size:14px; }
        .print-header p { margin:2px 0; font-size:10px; }
        .print-table { width:100%; border-collapse:collapse; margin-top:12px; }
        .print-table th, .print-table td { border:1px solid #333; padding:4px 6px; text-align:left; font-size:10px; }
        .print-table th { background:#eee; }
        .no-print { text-align:center; margin-bottom:16px; }
        @media print { .no-print { display:none !important; } @page { margin:0; } }
        .urdu-text { font-family:'Noto Nastaliq Urdu',serif; direction:rtl; }
    </style>
</head>
<body onload="window.print()">
    <div class="no-print" style="padding:16px;">
        <button onclick="window.print()">Print</button> | 
        <a href="?id=<?= $id ?>&format=a5">A5 Format</a> | 
        <a href="<?= url('gold-receipts/show.php?id=' . $id) ?>">Back</a>
    </div>
    <div class="print-container <?= $format === 'a5' ? 'format-a5' : 'format-slip' ?>">
        <div class="print-header">
            <h2><?= htmlspecialchars($wsName) ?></h2>
            <h3 class="urdu-text"><?= htmlspecialchars($wsNameUrdu) ?></h3>
            <p><?= htmlspecialchars($wsAddress) ?> | Phone: <?= htmlspecialchars($wsPhone) ?> | <?= htmlspecialchars($wsCity) ?></p>
        </div>
        <div style="display:flex;justify-content:space-between;">
            <div><strong>Receipt:</strong> <?= htmlspecialchars($receipt['receipt_no']) ?></div>
            <div><strong>Date:</strong> <?= formatDate($receipt['receipt_date']) ?></div>
        </div>
        <p><strong>Party:</strong> <?= htmlspecialchars($receipt['customer_name'] ?? '') ?> | <?= htmlspecialchars($receipt['customer_phone'] ?? '') ?></p>

        <table class="print-table">
            <tr><th>#</th><th>Description</th><th>Gross (g)</th><th>Ratti</th><th>Khalis (g)</th></tr>
            <?php $i=1; foreach ($items as $item): ?>
            <tr><td><?= $i++ ?></td><td><?= htmlspecialchars($item['description'] ?? '-') ?></td><td class="text-right"><?= number_format($item['gross_weight'],3) ?></td><td class="text-right"><?= number_format($item['ratti_impurity'],3) ?></td><td class="text-right"><?= number_format($item['khalis_weight'],3) ?></td></tr>
            <?php endforeach; ?>
            <tr style="font-weight:700;border-top:2px solid #000;">
                <td colspan="2">Total</td>
                <td class="text-right"><?= number_format($receipt['total_gross_weight'],3) ?></td>
                <td></td>
                <td class="text-right"><?= number_format($receipt['total_khalis_weight'],3) ?></td>
            </tr>
        </table>

        <div style="margin-top:16px;text-align:center;font-size:8px;">
            Generated by M.J Casting Management System
        </div>
    </div>
</body>
</html>