<?php
require_once __DIR__ . '/../config.php';
requireAuth();
require_once __DIR__ . '/../functions/gold_calculations.php';
ensureInvoiceMultipleDateColumns();
$pageTitle='Multiple Invoice Details';
$id=(int)query('id',0); $db=getDB();
$stmt=$db->prepare("SELECT im.*, c.name as customer_name, c.phone as customer_phone FROM invoice_multiple im LEFT JOIN customers c ON c.id=im.customer_id WHERE im.id=?"); $stmt->execute([$id]); $invoice=$stmt->fetch();
if(!$invoice){ setFlash('error','Multiple invoice not found.'); redirect('invoice-multiple/index.php'); }
$stmt=$db->prepare("SELECT *, COALESCE(item_date, (SELECT invoice_date FROM invoice_multiple WHERE id = ?)) AS row_date FROM invoice_multiple_items WHERE invoice_multiple_id=? ORDER BY COALESCE(item_date, (SELECT invoice_date FROM invoice_multiple WHERE id = ?)), id"); $stmt->execute([$id, $id, $id]); $items=$stmt->fetchAll();
$stmt=$db->prepare("SELECT *, COALESCE(receive_date, (SELECT invoice_date FROM invoice_multiple WHERE id = ?)) AS row_date FROM invoice_multiple_receives WHERE invoice_multiple_id=? ORDER BY COALESCE(receive_date, (SELECT invoice_date FROM invoice_multiple WHERE id = ?)), id"); $stmt->execute([$id, $id, $id]); $receives=$stmt->fetchAll();
require_once __DIR__ . '/../includes/header.php';
?>
<div class="page-header"><div class="page-title-group"><h1><?= htmlspecialchars($invoice['invoice_no']) ?></h1><p class="font-urdu" style="margin-top:4px;">ملٹی بل تفصیلات</p></div><div class="page-actions"><?php if($invoice['status']==='active'): ?><a href="<?= url('invoice-multiple/edit.php?id='.$id) ?>" class="btn btn-primary"><i class="bi bi-pencil"></i> Edit</a><?php endif; ?><a href="<?= url('invoice-multiple/print.php?id='.$id) ?>" class="btn btn-success"><i class="bi bi-printer"></i> Print</a><?php if($invoice['status']==='active'): ?><a href="<?= url('invoice-multiple/delete.php?id='.$id) ?>" class="btn btn-danger" onclick="return confirm('Cancel this multiple invoice?')"><i class="bi bi-trash"></i> Cancel</a><?php endif; ?><a href="<?= url('invoice-multiple/index.php') ?>" class="btn btn-outline"><i class="bi bi-arrow-left"></i> Back</a></div></div>
<div class="invoice-detail-grid"><div class="detail-card"><h3>Invoice Information</h3><div class="detail-row"><span class="detail-label">Invoice No</span><span class="detail-value"><?= htmlspecialchars($invoice['invoice_no']) ?></span></div><div class="detail-row"><span class="detail-label">Book No</span><span class="detail-value"><?= htmlspecialchars($invoice['manual_book_no'] ?: '-') ?></span></div><div class="detail-row"><span class="detail-label">Date</span><span class="detail-value"><?= formatDate($invoice['invoice_date']) ?></span></div><div class="detail-row"><span class="detail-label">Type</span><span class="detail-value"><span class="badge bg-info"><?= ucfirst($invoice['invoice_type']) ?></span></span></div><div class="detail-row"><span class="detail-label">Status</span><span class="detail-value"><span class="badge <?= $invoice['status']==='active'?'bg-success':'bg-danger' ?>"><?= ucfirst($invoice['status']) ?></span></span></div></div><div class="detail-card"><h3>Party</h3><div class="detail-row"><span class="detail-label">Name</span><span class="detail-value"><a href="<?= url('customers/show.php?id='.$invoice['customer_id']) ?>" style="color:var(--gold-primary);"><?= htmlspecialchars($invoice['customer_name'] ?? 'N/A') ?></a></span></div><div class="detail-row"><span class="detail-label">Phone</span><span class="detail-value"><?= htmlspecialchars($invoice['customer_phone'] ?? '-') ?></span></div></div></div>
<div class="stats-grid" style="margin-top:24px;"><div class="stat-card"><div class="stat-label">Total Casting</div><div class="stat-value"><?= number_format($invoice['total_casting_weight'],3) ?> g</div></div><div class="stat-card"><div class="stat-label">Gold Khalis</div><div class="stat-value"><?= number_format($invoice['total_gold_khalis'],3) ?> g</div></div><div class="stat-card"><div class="stat-label">Effective Given</div><div class="stat-value"><?= number_format($invoice['effective_gold'],3) ?> g</div></div><div class="stat-card"><div class="stat-label">Received</div><div class="stat-value"><?= number_format($invoice['total_received_khalis'],3) ?> g</div></div><div class="stat-card"><div class="stat-label">Previous</div><div class="stat-value"><?= number_format($invoice['previous_balance'],3) ?> g</div></div><div class="stat-card"><div class="stat-label">Remaining</div><div class="stat-value" style="color:<?= $invoice['remaining_balance']<0?'var(--error)':'var(--success)' ?>;"><?= number_format($invoice['remaining_balance'],3) ?> g</div></div></div>
<div class="card" style="padding:24px;margin-top:24px;"><h3 style="font-family:'Playfair Display',serif;margin-bottom:16px;color:var(--gold-primary);">Gold Calculation Rows</h3><div class="table-container"><table><thead><tr><th>Date</th><th>Description</th><th class="text-right">Casting</th><th class="text-right">Ratti</th><th class="text-right">Rate</th><th class="text-right">Waste</th><th class="text-right">Total</th><th class="text-right">Male Waste</th><th class="text-right">Khalis</th><th class="text-right">RP Wt</th><th class="text-right">Casting Wt</th><th class="text-right">Effective</th></tr></thead><tbody><?php foreach($items as $it): ?><tr><td><?= formatDate($it['row_date']) ?></td><td><?= htmlspecialchars($it['description'] ?: '-') ?></td><td class="text-right mono"><?= number_format($it['casting_weight'],3) ?></td><td class="text-right mono"><?= number_format($it['ratti'],3) ?></td><td class="text-right mono"><?= number_format($it['ratti_rate'],3) ?></td><td class="text-right mono"><?= number_format($it['waste_weight'],3) ?></td><td class="text-right mono"><?= number_format($it['total_weight'],3) ?></td><td class="text-right mono"><?= number_format($it['male_waste'],3) ?></td><td class="text-right mono"><?= number_format($it['gold_khalis'],3) ?></td><td class="text-right mono"><?= number_format($it['rp_mazdori_weight'],3) ?></td><td class="text-right mono"><?= number_format($it['casting_mazdori_weight'],3) ?></td><td class="text-right mono" style="color:var(--gold-bright);font-weight:700;"><?= number_format($it['effective_gold'],3) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr style="font-weight:700;background:var(--bg-surface);"><td colspan="2">Total</td><td class="text-right mono"><?= number_format($invoice['total_casting_weight'],3) ?></td><td></td><td></td><td class="text-right mono"><?= number_format($invoice['total_waste_weight'],3) ?></td><td class="text-right mono"><?= number_format($invoice['total_weight'],3) ?></td><td class="text-right mono"><?= number_format($invoice['total_male_waste'],3) ?></td><td class="text-right mono"><?= number_format($invoice['total_gold_khalis'],3) ?></td><td class="text-right mono"><?= number_format($invoice['total_rp_mazdori_weight'],3) ?></td><td class="text-right mono"><?= number_format($invoice['total_casting_mazdori_weight'],3) ?></td><td class="text-right mono"><?= number_format($invoice['effective_gold'],3) ?></td></tr></tfoot></table></div></div>
<?php if(!empty($receives)): ?><div class="card" style="padding:24px;margin-top:24px;"><h3 style="font-family:'Playfair Display',serif;margin-bottom:16px;color:var(--gold-primary);">Gold Received Rows</h3><div class="table-container"><table><thead><tr><th>Date</th><th>Description</th><th class="text-right">Gross</th><th class="text-right">Ratti</th><th class="text-right">Khalis</th></tr></thead><tbody><?php foreach($receives as $r): ?><tr><td><?= formatDate($r['row_date']) ?></td><td><?= htmlspecialchars($r['description'] ?: '-') ?></td><td class="text-right mono"><?= number_format($r['gross_weight'],3) ?></td><td class="text-right mono"><?= number_format($r['ratti_impurity'],3) ?></td><td class="text-right mono text-success"><?= number_format($r['khalis_weight'],3) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr style="font-weight:700;background:var(--bg-surface);"><td colspan="2">Total</td><td></td><td></td><td class="text-right mono text-success"><?= number_format($invoice['total_received_khalis'],3) ?></td></tr></tfoot></table></div></div><?php endif; ?>
<?php if($invoice['remarks']): ?><div class="card" style="padding:20px;margin-top:24px;"><strong>Remarks:</strong> <?= htmlspecialchars($invoice['remarks']) ?></div><?php endif; ?>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
